class MptConfig(MptConfig):
    def __init__(
        self,
        d_model: int = 2048,
        n_heads: int = 16,
        n_layers: int = 24,
        expansion_ratio: int = 4,
        max_seq_len: int = 2048,
        vocab_size: int = 50368,
        resid_pdrop: float = 0.0,
        layer_norm_epsilon: float = 1e-5,
        emb_pdrop: float = 0.0,
        learned_pos_emb: bool = True,
        attn_config: MptAttentionConfig = None,
        init_device: str = "cpu",
        logit_scale: Optional[Union[float, str]] = None,
        no_bias: bool = True,
        verbose: int = 0,
        embedding_fraction: float = 1.0,
        norm_type: str = "low_precision_layernorm",
        use_cache: bool = False,
        initializer_range=0.02,
        **kwargs,
    ):

        super().__init__(
            d_model,
            n_heads,
            n_layers,
            expansion_ratio,
            max_seq_len,
            vocab_size,
            resid_pdrop,
            layer_norm_epsilon,
            emb_pdrop,
            learned_pos_emb,
            attn_config,
            init_device,
            logit_scale,
            no_bias,
            verbose,
            embedding_fraction,
            norm_type,
            use_cache,
            initializer_range,
            **kwargs,
        )
